language: go
go:
 - 1.7
 - tip
 
script:  
 - "go build -o bin/vscale -i ."
  
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: bin/vscale
  skip_cleanup: true
  on:
    repo: lestex/vscalecli
    tags: true