language: go
go:
 - 1.7
 - 1.8
 - tip
 
script:  
 - "go build -o bin/vscale -i ."

notifications:
  email: $EMAIL
  on_success: always
  on_failure: always
  
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: bin/vscale
  skip_cleanup: true
  on:
    repo: lestex/vscalecli
    tags: true
